export const CONTACT = {
  name: "Mark Dalton",
  title: "Founder · Developer",
  company: "Costa Rica Luxury Real Estate",
  address: "Manuel Antonio, Costa Rica",
  phoneCr: "+506 8887-0547",
  phoneCrHref: "tel:+50688870547",
  phoneUs: "+1 954-931-1995",
  phoneUsHref: "tel:+19549311995",
  emailMarave: "mark@marave.com",
  emailMaraveHref: "mailto:mark@marave.com",
  emailCrlre: "mark@crlre.com",
  emailCrlreHref: "mailto:mark@crlre.com",
  website: "crlre.com",
  websiteHref: "https://crlre.com",
  propertiesHref: "https://crlre.com/properties/",
} as const;
