// Auto-synced from crlre.com/properties on July 8, 2026.
import type { Listing } from "./listings";

export const LISTINGS_DATA = [
  {
    slug: "profitable-income-generating-farm-with-lucrative-opportunities",
    href: "https://crlre.com/properties/profitable-income-generating-farm-with-lucrative-opportunities/",
    tag: "Commercial",
    image: "https://crlre.com/wp-content/uploads/44-hectare-farm-in-Parrita-Costa-Rica-1-e1771361535182.jpeg",
    alt: "44-hectare farm in Parrita, Costa Rica",
    location: "Quepos Puntarenas",
    title: "44-hectare farm in Parrita, Costa Rica",
    price: "$725,000 (USD)",
    specs: [{ label: "440,000 m", suffix: "" }],
    excerpt: "Discover this exceptional opportunity to own a 44-hectare farm in Parrita, Costa Rica. This property is currently a thriving palm oil plantation with an impressive...",
    sold: false,
    featured: true,
  },
  {
    slug: "new-construction-gorgeous-tropical-home-in-exclusive-gated-community",
    href: "https://crlre.com/properties/new-construction-gorgeous-tropical-home-in-exclusive-gated-community/",
    tag: "Commercial",
    image: "https://crlre.com/wp-content/uploads/CASA-BLANCA-23-1-e1771361943853.jpeg",
    alt: "Casa Blanca– Matapalo, Puntarenas",
    location: "Matapalo Puntarenas · Matapalo",
    title: "Casa Blanca– Matapalo, Puntarenas",
    price: "$1,295,000",
    specs: [{ label: "5", suffix: " beds" }, { label: "5", suffix: " baths" }, { label: "5,000 m", suffix: "" }],
    excerpt: "This brand-new construction in the exclusive gated community of Villas Brisas Del Mar, is truly a paradise waiting for you! Nestled in the lush jungle...",
    sold: false,
    featured: true,
  },
  {
    slug: "casa-jasmine-la-reserva-manuel-antonio",
    href: "https://crlre.com/properties/casa-jasmine-la-reserva-manuel-antonio/",
    tag: "Private Home",
    image: "https://crlre.com/wp-content/uploads/jasmine09.jpg",
    alt: "Casa Jasmine – La Reserva, Manuel Antonio",
    location: "La Reserva · Manuel Antonio",
    title: "Casa Jasmine – La Reserva, Manuel Antonio",
    price: "$3,550,000 (USD)",
    specs: [{ label: "8", suffix: " beds" }, { label: "8.5", suffix: " baths" }, { label: "930 m", suffix: "" }],
    excerpt: "Nestled in the heart of the verdant jungles of Manuel Antonio, Costa Rica, lies an extraordinary property that exudes elegance and sophistication. Welcome to your...",
    sold: false,
    featured: true,
  },
  {
    slug: "brisas-del-golfo",
    href: "https://crlre.com/properties/brisas-del-golfo/",
    tag: "Condo/Villa",
    image: "https://crlre.com/wp-content/uploads/CASA-MEL-MATAPALO-69-e1771358932811.jpg",
    alt: "Casa Mel, Residencial Villas del Mar, Matapalo, Puntarenas",
    location: "Palma Quemada · Costa Rica",
    title: "Casa Mel, Residencial Villas del Mar, Matapalo, Puntarenas",
    price: "$1,490,000",
    specs: [{ label: "6", suffix: " beds" }, { label: "6", suffix: " baths" }, { label: "5,000 m", suffix: "" }],
    excerpt: "Escape to the laid-back charm of Brisas Del Mar in Palma Quemada, Costa Rica, where this enchanting 5000m2 property awaits. Embraced by lush greenery and...",
    sold: false,
    featured: true,
  },
  {
    slug: "commercial-lot-with-600-m2-building-off-the-costenara",
    href: "https://crlre.com/properties/commercial-lot-with-600-m2-building-off-the-costenara/",
    tag: "Commercial",
    image: "https://crlre.com/wp-content/uploads/COMMERCIAL-LOT-with-600-m2-Building-off-the-Costanera-4-1-e1741365446537.jpg",
    alt: "COMMERCIAL LOT with 600 m2 Building off the Costanera",
    location: "Palma Quemada · Costa Rica",
    title: "COMMERCIAL LOT with 600 m2 Building off the Costanera",
    price: "$1,350,000",
    specs: [{ label: "8,527 m", suffix: "" }],
    excerpt: "Discover this spectacular investment opportunity situated right off the Costanera in Palma Quemada, Costa Rica! This expansive 8,527 m2 lot with a versatile 600 m2...",
    sold: false,
    featured: true,
  },
  {
    slug: "exclusive-residential-lots-ready-for-construction-mls-7ex104",
    href: "https://crlre.com/properties/exclusive-residential-lots-ready-for-construction-mls-7ex104/",
    tag: "Lot & Land",
    image: "https://crlre.com/wp-content/uploads/PHOTO-2024-07-04-16-16-26-13.jpg",
    alt: "EXCLUSIVE Residential Lots – Ready for Construction! (MLS #7EX104)",
    location: "Matapalo · Costa Rica",
    title: "EXCLUSIVE Residential Lots – Ready for Construction! (MLS #7EX104)",
    price: "$Starting at $110,000 (USD)",
    specs: [{ label: "5,000 m", suffix: "" }],
    excerpt: "Discover unparalleled tranquility in Matapalo, Costa Rica, with these exclusive residential lots, each sprawling over 5,000 square meters. Nestled within an exclusive gated community, these...",
    sold: false,
    featured: true,
  },
  {
    slug: "25891",
    href: "https://crlre.com/properties/25891/",
    tag: "Lot & Land",
    image: "https://crlre.com/wp-content/uploads/LAND-VILLAS-DEL-MAR-3-e1741289921175.jpg",
    alt: "Villas Brisas Del Mar – Exclusive Residential Lots with Owner Financing in Palma Quemada, Costa Rica",
    location: "Villas Brisas del Mar · Costa Rica",
    title: "Villas Brisas Del Mar – Exclusive Residential Lots with Owner Financing in Palma Quemada, Costa Rica",
    price: "$225,000 - $275,000 (USD)",
    specs: [],
    excerpt: "Welcome to Villas Brisas Del Mar, a remarkable investment opportunity that is designed to turn your dreams into a reality! This visionary project offers an...",
    sold: false,
    featured: true,
  },
  {
    slug: "1-bedroom-condo-with-pool-hacienda-pacifica",
    href: "https://crlre.com/properties/1-bedroom-condo-with-pool-hacienda-pacifica/",
    tag: "Condo/Villa",
    image: "https://crlre.com/wp-content/uploads/4-Hacienda-Pacifica-Single-Costa-Rica-Luxury-Real-Estate.jpg",
    alt: "1 Bedroom Condo with Pool • Hacienda Pacifica",
    location: "Quepos Puntarenas",
    title: "1 Bedroom Condo with Pool • Hacienda Pacifica",
    price: "$99,000",
    specs: [{ label: "1", suffix: " beds" }, { label: "1", suffix: " baths" }, { label: "600 SF m", suffix: "" }],
    excerpt: "Great starter home and or 1st investment opportunity with little money out of pocket. 1 Bedroom, 1 Full bathroom condo in a gated development with...",
    sold: false,
    featured: false,
  },
  {
    slug: "1523-mts-manuel-antonio-commercial-lot",
    href: "https://crlre.com/properties/1523-mts-manuel-antonio-commercial-lot/",
    tag: "Lot & Land",
    image: "https://crlre.com/wp-content/uploads/Properties/Biblos-Lot-Manuel-Antonio/3-Commercial-Lot-Manuel-Antonio-Biblos-Costa-Rica-Luxury-Real-Estate.jpg",
    alt: "1,523 MTS Manuel Antonio Commercial Lot",
    location: "Manuel Antonio Puntarenas",
    title: "1,523 MTS Manuel Antonio Commercial Lot",
    price: "$ 350,000",
    specs: [],
    excerpt: "MIXED USE COMMERCIAL LAND FOR SALE (Retail Stores, Souvenir Shops, Villas, Condos, Restaurants) This rectangular lot measures 20 MTS with direct road frontage and goes...",
    sold: false,
    featured: false,
  },
  {
    slug: "13-hectares-development-opportunity-in-herradura",
    href: "https://crlre.com/properties/13-hectares-development-opportunity-in-herradura/",
    tag: "Commercial",
    image: "https://crlre.com/wp-content/uploads/23-H2-Herradura-Development-Development.jpg",
    alt: "13 Hectares Development Opportunity in Herradura",
    location: "Herrradura",
    title: "13 Hectares Development Opportunity in Herradura",
    price: "$2,300,000",
    specs: [],
    excerpt: "13 Hectares (32 acres) of Development land permitted for commercial and residential construction only 2 km from Los Sueños Golf Resort & Marina & Herradura...",
    sold: false,
    featured: false,
  },
  {
    slug: "17-acres-private-estate-with-two-homes-with-panoramic-views",
    href: "https://crlre.com/properties/17-acres-private-estate-with-two-homes-with-panoramic-views/",
    tag: "Private Home",
    image: "https://crlre.com/wp-content/uploads/17-Acres-Private-Estate-with-two-Homes-with-Panoramic-Views-186.jpg",
    alt: "17 Acres Private Estate with two Homes with Panoramic Views",
    location: "Dominical",
    title: "17 Acres Private Estate with two Homes with Panoramic Views",
    price: "$1,925,000",
    specs: [{ label: "4", suffix: " beds" }, { label: "4.5", suffix: " baths" }, { label: "6,700 Sq.Ft. m", suffix: "" }],
    excerpt: "Location: Portalon, Dominical, Costa Rica This brand-new luxury property in Portalon is an exceptional estate nestled in 17 acres of lush primary and secondary forest. The...",
    sold: false,
    featured: false,
  },
  {
    slug: "18-75-acres-ocean-view-easy-access",
    href: "https://crlre.com/properties/18-75-acres-ocean-view-easy-access/",
    tag: "Lot & Land",
    image: "https://crlre.com/wp-content/uploads/18.75-ACRES-PLATANILLO-3-e1651942267734.jpg",
    alt: "18.75 ACRES – Ocean View, Easy Access",
    location: "Uvita · Puntarenas",
    title: "18.75 ACRES – Ocean View, Easy Access",
    price: "$369,000",
    specs: [],
    excerpt: "This 18-acre property is located in Platanillo less than 5 min from the paved road and sits at approx 1000 ft elevation. The property has...",
    sold: false,
    featured: false,
  },
  {
    slug: "hacienda-pacifica-2-bedroom-condo",
    href: "https://crlre.com/properties/hacienda-pacifica-2-bedroom-condo/",
    tag: "Condo/Villa",
    image: "https://crlre.com/wp-content/uploads/29-Hacienda-Pacifica-Costa-Rica-Luxury-Real-Estate.jpg",
    alt: "2 Bedroom Condo with Pool • Hacienda Pacifica",
    location: "Quepos Puntarenas",
    title: "2 Bedroom Condo with Pool • Hacienda Pacifica",
    price: "$200,000",
    specs: [{ label: "2", suffix: " beds" }, { label: "2", suffix: " baths" }, { label: "1,614 SF m", suffix: "" }],
    excerpt: "This 1614 sq. ft. villa is located in a desirable gated community with a premium location overlooking the pool & landscaped gardens. All living spaces...",
    sold: false,
    featured: false,
  },
  {
    slug: "3-villas-in-finca-se-ve-bien",
    href: "https://crlre.com/properties/3-villas-in-finca-se-ve-bien/",
    tag: "Private Home",
    image: "https://crlre.com/wp-content/uploads/VILLAS-SE-VE-BIEN-7.jpg",
    alt: "3 Villas in Finca Se Ve Bien",
    location: "Manuel Antonio · Puntarenas",
    title: "3 Villas in Finca Se Ve Bien",
    price: "$539,000",
    specs: [{ label: "5", suffix: " beds" }, { label: "5", suffix: " baths" }, { label: "330 M2 m", suffix: "" }],
    excerpt: "Retire Early! Live in 1 Villa and rent the others as short term or long term rentals to pay for your lifestyle and all your...",
    sold: false,
    featured: false,
  },
  {
    slug: "285000-300-degree-views-ocean-mountain",
    href: "https://crlre.com/properties/285000-300-degree-views-ocean-mountain/",
    tag: "Lot & Land",
    image: "https://crlre.com/wp-content/uploads/Ridges-crlre-4-e1663194568718.jpg",
    alt: "300 DEGREE VIEWS! OCEAN & MOUNTAIN!",
    location: "Portalon Puntarenas",
    title: "300 DEGREE VIEWS! OCEAN & MOUNTAIN!",
    price: "$285,000",
    specs: [{ label: "4440m m", suffix: "" }],
    excerpt: "The Hills of Portalon, a coveted community in the mountains over looking the nicest stretch of beach for miles and miles. Portalon is the next...",
    sold: false,
    featured: false,
  },
  {
    slug: "5000-sf-modern-ocean-view-home-architectural-masterpiece",
    href: "https://crlre.com/properties/5000-sf-modern-ocean-view-home-architectural-masterpiece/",
    tag: "Private Home",
    image: "https://crlre.com/wp-content/uploads/OCEAN-VIEW-PORTALÓN-38-e1635182546717.jpg",
    alt: "5,000 SF Modern Ocean View Home – Architectural Masterpiece",
    location: "Portalón · Quepos",
    title: "5,000 SF Modern Ocean View Home – Architectural Masterpiece",
    price: "$1,249,000",
    specs: [{ label: "4", suffix: " beds" }, { label: "4", suffix: " baths" }, { label: "5,000 SF m", suffix: "" }],
    excerpt: "Located in the gated community of Portasol, this home is 10 minutes to Playa Matapalo, 20 minutes to Dominical and 30 minutes to Quepos/Manuel Antonio...",
    sold: false,
    featured: false,
  },
  {
    slug: "75-acre-mountain-with-ocean-waterfalls-springs",
    href: "https://crlre.com/properties/75-acre-mountain-with-ocean-waterfalls-springs/",
    tag: "Lot & Land",
    image: "https://crlre.com/wp-content/uploads/2-Coronado-75Acres-Waterfalls-Ocean.jpg",
    alt: "75 Acre Mountain with Ocean, Waterfalls & Springs",
    location: "Coronado · OSA",
    title: "75 Acre Mountain with Ocean, Waterfalls & Springs",
    price: "$1.3 Million",
    specs: [],
    excerpt: "If you are looking for ocean views, waterfalls, natural springs, rivers & privacy; then this is the perfect opportunity for you. Instead of buying a...",
    sold: false,
    featured: false,
  },
  {
    slug: "84-hectare-mountain-top-land",
    href: "https://crlre.com/properties/84-hectare-mountain-top-land/",
    tag: "Lot & Land",
    image: "https://crlre.com/wp-content/uploads/Properties/84-Hectare-Mountain-top-land/84-Hectare-Mountain-Top-Land-26-e1518060978551-370x300.jpg",
    alt: "84 Hectare Mountain Top Land",
    location: "Manuel Antonio · Puntarenas",
    title: "84 Hectare Mountain Top Land",
    price: "$6.8M",
    specs: [],
    excerpt: "REDUCED FROM $10,080,000 USD This is truly an exceptional opportunity for a world-class real estate development in Manuel Antonio, the No.1 most visited area in...",
    sold: false,
    featured: false,
  },
  {
    slug: "beachfront-condo-2-bedroom-4d",
    href: "https://crlre.com/properties/beachfront-condo-2-bedroom-4d/",
    tag: "Condo/Villa",
    image: "https://crlre.com/wp-content/uploads/Elan-at-ballena-beach.jpeg",
    alt: "BEACHFRONT Condo 2 Bedroom #4D",
    location: "Uvita",
    title: "BEACHFRONT Condo 2 Bedroom #4D",
    price: "$650,000",
    specs: [{ label: "2", suffix: " beds" }, { label: "2.5", suffix: " baths" }, { label: "1,776 SQ. FT. m", suffix: "" }],
    excerpt: "The Elan at Ballena beach condominiums are the most luxurious condos in Costa Ballena, Costa Rica. Elan is the only development with private direct beach...",
    sold: false,
    featured: false,
  },
  {
    slug: "boutique-hotel-with-11-condo-residences",
    href: "https://crlre.com/properties/boutique-hotel-with-11-condo-residences/",
    tag: "Condo/Villa",
    image: "https://crlre.com/wp-content/uploads/Display-Photo.jpg",
    alt: "Boutique Hotel Condominium Complex",
    location: "Manuel Antonio Puntarenas",
    title: "Boutique Hotel Condominium Complex",
    price: "$ 1,295,000 Make an Offer!",
    specs: [{ label: "11", suffix: " beds" }, { label: "11.5", suffix: " baths" }],
    excerpt: "Reduced from $1.6 Million This is a unique opportunity to invest in a boutique hotel in Manuel Antonio with property that has 10 condo residences...",
    sold: false,
    featured: false,
  },
  {
    slug: "butterfly-breeze-villa-uvita-ocean-view",
    href: "https://crlre.com/properties/butterfly-breeze-villa-uvita-ocean-view/",
    tag: "Ocean View",
    image: "https://crlre.com/wp-content/uploads/Butterfly-Breeze-Villa_CRLRE-5.jpeg",
    alt: "Butterfly Breeze Villa, Uvita Ocean View",
    location: "Uvita · Puntarenas",
    title: "Butterfly Breeze Villa, Uvita Ocean View",
    price: "$920,000",
    specs: [{ label: "4", suffix: " beds" }, { label: "4", suffix: " baths" }, { label: "3800 pies cuadrado m", suffix: "" }],
    excerpt: "Butterfly Breeze Villa sits at 700 feet elevation on a very well maintained road, just minutes to the centre of town. Drive through the gate...",
    sold: false,
    featured: false,
  },
  {
    slug: "casa-cielo-contemporary-home-plus-adjacent-lot-with-caretakers-house-for-sale-in-manuel-antonio-mls-7vr101",
    href: "https://crlre.com/properties/casa-cielo-contemporary-home-plus-adjacent-lot-with-caretakers-house-for-sale-in-manuel-antonio-mls-7vr101/",
    tag: "Sale",
    image: "https://crlre.com/wp-content/uploads/transitional-1692243971.59889.jpg",
    alt: "Casa Cielo – Contemporary Home Plus Adjacent Lot With Caretaker’s House For Sale In Manuel Antonio! (MLS #7VR101)",
    location: "Manuel Antonio · Costa Rica",
    title: "Casa Cielo – Contemporary Home Plus Adjacent Lot With Caretaker’s House For Sale In Manuel Antonio! (MLS #7VR101)",
    price: "$729,000 (USD)",
    specs: [{ label: "6", suffix: " beds" }, { label: "6", suffix: " baths" }, { label: "7,000 sq ft m", suffix: "" }],
    excerpt: "Casa Cielo brings the classic elements of modern architecture, like enormous windows and an open-concept living, to a jungle setting that maximizes the beauty of...",
    sold: false,
    featured: false,
  },
  {
    slug: "casa-cielo-main-house-plus-4-separate-rentals",
    href: "https://crlre.com/properties/casa-cielo-main-house-plus-4-separate-rentals/",
    tag: "Private Home",
    image: "https://crlre.com/wp-content/uploads/3-Casa-Ceilo-Costa-Rica-Luxury-Real-Estate.jpeg",
    alt: "Casa Cielo, Main House Plus 4 separate rentals!",
    location: "Manuel Antonio",
    title: "Casa Cielo, Main House Plus 4 separate rentals!",
    price: "$795,000",
    specs: [{ label: "6", suffix: " beds" }, { label: "6.5", suffix: " baths" }, { label: "7,000 Sq.Ft. m", suffix: "" }],
    excerpt: "This luxurious, contemporary home in the heart of Manuel Antonio, is near one of the most famous beaches in Costa Rica. This home works beautifully...",
    sold: false,
    featured: false,
  },
  {
    slug: "casa-colibri-•-3-bedroom-villa-with-in-law-suite",
    href: "https://crlre.com/properties/casa-colibri-%e2%80%a2-3-bedroom-villa-with-in-law-suite/",
    tag: "Private Home",
    image: "https://crlre.com/wp-content/uploads/1-Casa-Colibri-3Bed-Villa-CRLRE.jpg",
    alt: "Casa Colibri • 3 Bedroom Villa with In-law Suite",
    location: "Quepos Puntarenas",
    title: "Casa Colibri • 3 Bedroom Villa with In-law Suite",
    price: "$285,000",
    specs: [{ label: "3", suffix: " beds" }, { label: "3.5", suffix: " baths" }, { label: "2,949 Sq.Ft m", suffix: "" }],
    excerpt: "This is a solid concrete construction home with a total of 3 bedrooms & 3.5 bathrooms along with an completely enclosed yard with two electronic...",
    sold: false,
    featured: false,
  },
  {
    slug: "casa-cristal-manuel-antonio",
    href: "https://crlre.com/properties/casa-cristal-manuel-antonio/",
    tag: "Ocean View",
    image: "https://crlre.com/wp-content/uploads/casa-cristal-50.jpg",
    alt: "Casa Cristal Manuel Antonio",
    location: "Manuel Antonio",
    title: "Casa Cristal Manuel Antonio",
    price: "$2,400,000",
    specs: [{ label: "3", suffix: " beds" }, { label: "6", suffix: " baths" }, { label: "562 sq m (sq ft) m", suffix: "" }],
    excerpt: "Casa Cristal of Manuel Antonio is the most unique estate home offered in this prestigious destination. Its location provides the most dramatic views of the...",
    sold: false,
    featured: false,
  },
  {
    slug: "casa-espanola-manuel-antonio-ocean-view",
    href: "https://crlre.com/properties/casa-espanola-manuel-antonio-ocean-view/",
    tag: "Ocean View",
    image: "https://crlre.com/wp-content/uploads/casa-española-6.jpg",
    alt: "Casa Española, Manuel Antonio ocean view",
    location: "Manuel Antonio",
    title: "Casa Española, Manuel Antonio ocean view",
    price: "$2,400,000",
    specs: [{ label: "8", suffix: " beds" }, { label: "8", suffix: " baths" }, { label: "10,000 SF. m", suffix: "" }],
    excerpt: "Casa Española truly is magnificent. Arranged over 4 floors, our villa provides privacy and comfort to both large and small groups alike. With 8 lavish bedroom...",
    sold: false,
    featured: false,
  },
  {
    slug: "casa-iconic-costa-verde",
    href: "https://crlre.com/properties/casa-iconic-costa-verde/",
    tag: "Ocean View",
    image: "https://crlre.com/wp-content/uploads/20-Casa-Iconic-Escaleras-Lujo-CRLRE.jpeg",
    alt: "Casa Iconic Costa Verde",
    location: "Dominical Puntarenas · Escaleras",
    title: "Casa Iconic Costa Verde",
    price: "$2,800,000",
    specs: [{ label: "5", suffix: " beds" }, { label: "7", suffix: " baths" }, { label: "10,000 Sq.Ft. m", suffix: "" }],
    excerpt: "Casa Iconic features the main house with 2 additional guest houses that can be accessed within the property or entered into separately. This modern home...",
    sold: false,
    featured: false,
  },
  {
    slug: "casa-ombak-in-luxurious-gated-community",
    href: "https://crlre.com/properties/casa-ombak-in-luxurious-gated-community/",
    tag: "Private Home",
    image: "https://crlre.com/wp-content/uploads/Casa-Ombak-in-Luxurious-Gated-Community-40-e1679088513314.jpeg",
    alt: "Casa Ombak in Luxurious Gated Community",
    location: "Dominical",
    title: "Casa Ombak in Luxurious Gated Community",
    price: "$3,500,000",
    specs: [{ label: "5", suffix: " beds" }, { label: "6", suffix: " baths" }, { label: "1.24 ACRES m", suffix: "" }],
    excerpt: "Location: Escaleras, Dominical, Costa Rica Located in the highly sought community of Escalaras, Casa Ombak truly is an amazing opportunity to own the top luxury home...",
    sold: false,
    featured: false,
  },
  {
    slug: "casa-ultimo-sueno",
    href: "https://crlre.com/properties/casa-ultimo-sueno/",
    tag: "Ocean View",
    image: "https://crlre.com/wp-content/uploads/72-Casa-Ultimo-Sueño-CRLRE-Uvita.jpg",
    alt: "Casa Ultimo Sueño",
    location: "Uvita",
    title: "Casa Ultimo Sueño",
    price: "$2,995,000",
    specs: [{ label: "6", suffix: " beds" }, { label: "8.5", suffix: " baths" }, { label: "558 M2 m", suffix: "" }],
    excerpt: "Location: Ballena, Uvita, Costa Rica Welcome to Casa Ultimo Sueño, the ultimate luxurious oasis located above the picturesque coastal town of Uvita, Costa Rica. This stunning...",
    sold: false,
    featured: false,
  },
  {
    slug: "casa-vista-royal-luxury-villa-uvita-costa-rica",
    href: "https://crlre.com/properties/casa-vista-royal-luxury-villa-uvita-costa-rica/",
    tag: "Condo/Villa",
    image: "https://crlre.com/wp-content/uploads/VISTA-ROYAL-109-e1749845678253.jpg",
    alt: "Casa Vista Royal Luxury Villa, Uvita, Costa Rica",
    location: "Uvita · Puntarenas",
    title: "Casa Vista Royal Luxury Villa, Uvita, Costa Rica",
    price: "$3,250,000 (USD)",
    specs: [{ label: "6", suffix: " beds" }, { label: "6", suffix: " baths" }, { label: "10,000 m² m", suffix: "" }],
    excerpt: "Discover Casa Vista Royal, a secluded luxury retreat in a private enclave just 3 minutes from downtown Uvita. Perched on a private hill, this stunning...",
    sold: false,
    featured: false,
  },
  {
    slug: "cielo-azul-villa",
    href: "https://crlre.com/properties/cielo-azul-villa/",
    tag: "Ocean View",
    image: "https://crlre.com/wp-content/uploads/Cielo-Azul-CRLRE-9-e1660081169355.jpg",
    alt: "Cielo Azul Villa",
    location: "Uvita · Puntarenas",
    title: "Cielo Azul Villa",
    price: "$2,250,000",
    specs: [{ label: "6", suffix: " beds" }, { label: "7", suffix: " baths" }, { label: "7,000 SF m", suffix: "" }],
    excerpt: "Reduced from $2,450,000 USD ($200k Savings) The Cielo Azul Villa (Blue Sky Villa) estate is an unsurpassed work of excellence sitting hillside in the Uvita...",
    sold: false,
    featured: false,
  },
  {
    slug: "eco-condos-for-sale-in-manuel-antonio",
    href: "https://crlre.com/properties/eco-condos-for-sale-in-manuel-antonio/",
    tag: "Condo/Villa",
    image: "https://crlre.com/wp-content/uploads/Eco-Condos-91-e1700860288658.jpeg",
    alt: "Eco Condos for Sale in Manuel Antonio",
    location: "Manuel Antonio · Puntarenas",
    title: "Eco Condos for Sale in Manuel Antonio",
    price: "$995,000.00 USD",
    specs: [{ label: "2 (Each Apartment)", suffix: " beds" }, { label: "Baths: 1 (Each Apartment)", suffix: " baths" }, { label: "8 Rentals - Investment opportunity! m", suffix: "" }],
    excerpt: "Centrally located just walking distance from the charming town of Quepos, Eco Condos within the gated community of Manuel Antonio Estates is a boutique apartment...",
    sold: false,
    featured: false,
  },
  {
    slug: "endless-memories-to-come-4-bed-home-and-two-guest-homes",
    href: "https://crlre.com/properties/endless-memories-to-come-4-bed-home-and-two-guest-homes/",
    tag: "Sale",
    image: "https://crlre.com/wp-content/uploads/Endless-Memories-To-Come-4-Bed-home-and-Two-Guest-homes-1.jpeg",
    alt: "Endless Memories To Come, 4 Bed home and Two Guest homes",
    location: "Portalon · Puntarenas",
    title: "Endless Memories To Come, 4 Bed home and Two Guest homes",
    price: "$1,540,000",
    specs: [{ label: "6", suffix: " beds" }, { label: "5", suffix: " baths" }, { label: "2.62 ACRES m", suffix: "" }],
    excerpt: "Reduced from $1,620,000 Your very own tropical paradise in the heart of Costa Rica. Prepare to be captivated by the enchanting beauty and endless adventure...",
    sold: false,
    featured: false,
  },
  {
    slug: "espadilla-ocean-club",
    href: "https://crlre.com/properties/espadilla-ocean-club/",
    tag: "Ocean View",
    image: "https://crlre.com/wp-content/uploads/Vacation-Rentals/Espadilla-Ocean-Clubl-VR/Espadilla-Ocean-Club-14.PNG",
    alt: "Espadilla Ocean Club",
    location: "Manuel Antonio Puntarenas",
    title: "Espadilla Ocean Club",
    price: "$ $495.00",
    specs: [{ label: "2", suffix: " beds" }, { label: "2", suffix: " baths" }],
    excerpt: "Accommodates 5 guest – 7 Bedrooms – 7 Bathrooms The Espadilla Ocean Club, Manuel Antonio’s only BEACHFRONT luxury rental villas, your steps from the renowned...",
    sold: false,
    featured: false,
  },
  {
    slug: "hilltop-seaview-estate-with-extra-building-site",
    href: "https://crlre.com/properties/hilltop-seaview-estate-with-extra-building-site/",
    tag: "Ocean View",
    image: "https://crlre.com/wp-content/uploads/32-Hilltop-Seaview-Estate-Hills-Portalon-CRLRE.jpg",
    alt: "Hilltop Seaview Estate with Extra Building Site",
    location: "Portalon Puntarenas",
    title: "Hilltop Seaview Estate with Extra Building Site",
    price: "$1,585,000",
    specs: [{ label: "4", suffix: " beds" }, { label: "4.5", suffix: " baths" }, { label: "4,305 Sq. Ft. (Plus pool & Jacuzzi, parking and paved drive) m", suffix: "" }],
    excerpt: "Perched on the top ridge of the Hills of Portalon, this is property you must see!",
    sold: false,
    featured: false,
  },
  {
    slug: "land-lots-for-sale-in-parrita-available-now",
    href: "https://crlre.com/properties/land-lots-for-sale-in-parrita-available-now/",
    tag: "Lot & Land",
    image: "https://crlre.com/wp-content/uploads/DAMAS-QUEPOS-3-e1771357087246.jpeg",
    alt: "Land Lots for Sale in Damas, Quepos – Available Now",
    location: "Damas 10 Minutes From Quepos",
    title: "Land Lots for Sale in Damas, Quepos – Available Now",
    price: "$85,000 (USD)",
    specs: [{ label: "5,000 m² m", suffix: "" }],
    excerpt: "5,000 m² lot for $85,000 Lot available in Damas, Quepos, Puntarenas, Costa Rica. The property is officially registered and surveyed with an approved cadastral plan....",
    sold: false,
    featured: false,
  },
  {
    slug: "penthouse-8a-resort-living",
    href: "https://crlre.com/properties/penthouse-8a-resort-living/",
    tag: "Condo/Villa",
    image: "https://crlre.com/wp-content/uploads/LOS-ALTOS-1-copy-2-1.jpg",
    alt: "Los Altos, Penthouse Living with Roof Top Hot Tub",
    location: "Manuel Antonio Puntarenas",
    title: "Los Altos, Penthouse Living with Roof Top Hot Tub",
    price: "$1,650,000",
    specs: [{ label: "4", suffix: " beds" }, { label: "3.5", suffix: " baths" }, { label: "4,300 Sq.Ft m", suffix: "" }],
    excerpt: "Panoramic Ocean Views in Manuel Antonio with a rolodex of amenities you can't live without",
    sold: false,
    featured: false,
  },
  {
    slug: "luxury-carabao-villa",
    href: "https://crlre.com/properties/luxury-carabao-villa/",
    tag: "Private Home",
    image: "https://crlre.com/wp-content/uploads/Luxury-Carabao-Villa-48-e1679332330613.jpeg",
    alt: "Luxury Carabao Villa",
    location: "Ballena · Costa Rica",
    title: "Luxury Carabao Villa",
    price: "$2,500,000",
    specs: [{ label: "4", suffix: " beds" }, { label: "5.5", suffix: " baths" }, { label: "0.16 ACRES m", suffix: "" }],
    excerpt: "Location: Ballena, Uvita, Costa Rica Welcome to your own personal paradise in Uvita! This spectacular luxury villa is the epitome of style, elegance, and convenience. Newly...",
    sold: false,
    featured: false,
  },
  {
    slug: "ocean-view-home-in-gated-community",
    href: "https://crlre.com/properties/ocean-view-home-in-gated-community/",
    tag: "Private Home",
    image: "https://crlre.com/wp-content/uploads/Ocean-View-Home-in-Gated-Community-10-e1671642366302.jpg",
    alt: "Ocean View Home in Gated Community",
    location: "Hatillo · Dominical",
    title: "Ocean View Home in Gated Community",
    price: "$849,000",
    specs: [{ label: "4", suffix: " beds" }, { label: "4.5", suffix: " baths" }, { label: "7.89 ACRES m", suffix: "" }],
    excerpt: "Location: Hatillo, Dominical, Costa Rica Two sides of the home are protected by white trunked tropical trees that give inspiration for the home’s design, “Casa Ramas:...",
    sold: false,
    featured: false,
  },
  {
    slug: "ocean-view-in-escalares-dominical",
    href: "https://crlre.com/properties/ocean-view-in-escalares-dominical/",
    tag: "Ocean View",
    image: "https://crlre.com/wp-content/uploads/escalares-CRLRE-16.jpg",
    alt: "Ocean View in Escalares, Dominical.",
    location: "Dominical · Puntarenas",
    title: "Ocean View in Escalares, Dominical.",
    price: "$1,375,000",
    specs: [{ label: "4", suffix: " beds" }, { label: "3", suffix: " baths" }, { label: "2.2 ACRES m", suffix: "" }],
    excerpt: "Location: Dominical, Costa Rica This brand new home in upscale Escalares comes with what everyone is looking for; privacy, ocean views, jungle setting, creek, high-speed internet,...",
    sold: false,
    featured: false,
  },
  {
    slug: "ocean-view-property-in-escaleras-village",
    href: "https://crlre.com/properties/ocean-view-property-in-escaleras-village/",
    tag: "Lot & Land",
    image: "https://crlre.com/wp-content/uploads/Ocean-View-Property-in-Escaleras-Village-7-e1695931016316.jpeg",
    alt: "Ocean View Property in Escaleras Village",
    location: "Dominical",
    title: "Ocean View Property in Escaleras Village",
    price: "$590,000",
    specs: [{ label: "1.56 ACRES m", suffix: "" }],
    excerpt: "Location: Escaleras, Dominical, Costa Rica Welcome to luxury living at the prestigious Escalares Village, an exclusive gated community located in the heart of Escalares. Boasting a...",
    sold: false,
    featured: false,
  },
  {
    slug: "ola-vista-•-luxury-home-•-dominical",
    href: "https://crlre.com/properties/ola-vista-%e2%80%a2-luxury-home-%e2%80%a2-dominical/",
    tag: "Sale",
    image: "https://crlre.com/wp-content/uploads/20-Ola-Vista-Dominicalito-CRLRE.jpg",
    alt: "Ola Vista • Luxury Home • Dominical",
    location: "Dominicalito",
    title: "Ola Vista • Luxury Home • Dominical",
    price: "$1,750,000",
    specs: [{ label: "4", suffix: " beds" }, { label: "4", suffix: " baths" }, { label: "5,382 Sq.Ft m", suffix: "" }],
    excerpt: "Casa Ola Vista is a stunning single-level, luxury 4-bedroom, 4-bathroom beach home featuring a front-row seat, looking over Dominicalito Bay and the sprawling Pacific Ocean...",
    sold: false,
    featured: false,
  },
  {
    slug: "paradise-in-uvita-jungle-and-ocean-view",
    href: "https://crlre.com/properties/paradise-in-uvita-jungle-and-ocean-view/",
    tag: "Lot & Land",
    image: "https://crlre.com/wp-content/uploads/Paradise-Uvita_CRLRE-20.jpeg",
    alt: "Paradise In Uvita, Jungle and Ocean View!",
    location: "Uvita · Puntarenas",
    title: "Paradise In Uvita, Jungle and Ocean View!",
    price: "$550,000",
    specs: [],
    excerpt: "This property is located hillside on the prestigious mountains of Uvita at 400ft above sea level, a short 10 minute drive up the hill on...",
    sold: false,
    featured: false,
  },
  {
    slug: "puerta-del-cielo-•-mixed-used-building",
    href: "https://crlre.com/properties/puerta-del-cielo-%e2%80%a2-mixed-used-building/",
    tag: "Commercial",
    image: "https://crlre.com/wp-content/uploads/28-puertadelcielo-crlre-quepos-marina-copy.jpg",
    alt: "Puerta del Cielo • Mixed Use Building",
    location: "Quepos Puntarenas",
    title: "Puerta del Cielo • Mixed Use Building",
    price: "$1,200,000",
    specs: [{ label: "10", suffix: " beds" }, { label: "10.5", suffix: " baths" }, { label: "750 M2 m", suffix: "" }],
    excerpt: "Puerta del Cielo was built in 2008 and has always been family owned and operated. The 4 story building with elevator access was designed as...",
    sold: false,
    featured: false,
  },
  {
    slug: "seaside-ocean-view-mansion-in-exclusive-dominical-community",
    href: "https://crlre.com/properties/seaside-ocean-view-mansion-in-exclusive-dominical-community/",
    tag: "Ocean View",
    image: "https://crlre.com/wp-content/uploads/Seaside-Ocean-View-Mansion-in-Exclusive-Neighborhood-Above-Dominical-Beach-28.jpg",
    alt: "Seaside Ocean View Mansion in Exclusive Dominical Community",
    location: "Dominical",
    title: "Seaside Ocean View Mansion in Exclusive Dominical Community",
    price: "$2,495,000",
    specs: [{ label: "10", suffix: " beds" }, { label: "7", suffix: " baths" }, { label: "2.35 acres m", suffix: "" }],
    excerpt: "Seaside Ocean View Mansion in Exclusive Neighborhood Above Dominical Beach This turn-key seaside mansion is located inside Ayacucho, one of the most exclusive private neighborhoods in...",
    sold: false,
    featured: false,
  },
  {
    slug: "stunning-new-open-concept-home-with-pool",
    href: "https://crlre.com/properties/stunning-new-open-concept-home-with-pool/",
    tag: "Private Home",
    image: "https://crlre.com/wp-content/uploads/25-Uvita-Jardines-Pool-Luxury-CRLRE.jpg",
    alt: "Stunning NEW Open Concept Home with Pool",
    location: "Uvita Puntarenas",
    title: "Stunning NEW Open Concept Home with Pool",
    price: "$309,900",
    specs: [{ label: "2", suffix: " beds" }, { label: "2.5", suffix: " baths" }, { label: "1,850 Sq. Ft. m", suffix: "" }],
    excerpt: "This brand new model home is located in the new master-planned community of Jardines Del Sol, in the heart of Uvita. This convenient location makes...",
    sold: false,
    featured: false,
  },
  {
    slug: "stunning-ocean-views-at-casa-perezoso",
    href: "https://crlre.com/properties/stunning-ocean-views-at-casa-perezoso/",
    tag: "Ocean View",
    image: "https://crlre.com/wp-content/uploads/Casa-Perezoso_CRLRE-2.jpg",
    alt: "Stunning Ocean Views at Casa Perezoso",
    location: "Dominical · Puntarenas",
    title: "Stunning Ocean Views at Casa Perezoso",
    price: "$1,150,000",
    specs: [{ label: "4", suffix: " beds" }, { label: "3.5", suffix: " baths" }, { label: "4,000 Sq.Ft. m", suffix: "" }],
    excerpt: "Reduced by $50,000 USD This Escaleras home is a must-see work of art. The house and its fittings were painstakingly handcrafted out of local timber...",
    sold: false,
    featured: false,
  },
  {
    slug: "suenos-pacificos-ocean-view-luxury-villa-in-las-olas-of-dominical",
    href: "https://crlre.com/properties/suenos-pacificos-ocean-view-luxury-villa-in-las-olas-of-dominical/",
    tag: "Ocean View",
    image: "https://crlre.com/wp-content/uploads/Suenos-Pacificos-Ocean-View-Luxury-Villa-in-Las-Olas-of-Dominical-65.jpg",
    alt: "Suenos Pacificos Ocean View Luxury Villa in Las Olas of Dominical",
    location: "Dominical",
    title: "Suenos Pacificos Ocean View Luxury Villa in Las Olas of Dominical",
    price: "$2,500,000",
    specs: [{ label: "3", suffix: " beds" }, { label: "4", suffix: " baths" }, { label: "1.24 Acres m", suffix: "" }],
    excerpt: "Suenos Pacificos Front Row Ocean View Luxury Villa in the Prestigious Las Olas of Dominical Discover what it means to live in the lap of...",
    sold: false,
    featured: false,
  },
  {
    slug: "tanager-villa-ocean-view-manuel-antonio",
    href: "https://crlre.com/properties/tanager-villa-ocean-view-manuel-antonio/",
    tag: "Ocean View",
    image: "https://crlre.com/wp-content/uploads/Y5I3999-Edit.jpg",
    alt: "Tanager Villa, Ocean View Manuel Antonio",
    location: "Manuel Antonio · Puntarenas",
    title: "Tanager Villa, Ocean View Manuel Antonio",
    price: "$899,000",
    specs: [{ label: "7", suffix: " beds" }, { label: "9", suffix: " baths" }, { label: "5,500 SF m", suffix: "" }],
    excerpt: "Amazing 7 Bedroom Tanager Villa, one of Manuel Antonio’s top vacation rentals, is now available for sale as a great option for those looking for...",
    sold: false,
    featured: false,
  },
  {
    slug: "the-elite-jade-house-in-escaleras",
    href: "https://crlre.com/properties/the-elite-jade-house-in-escaleras/",
    tag: "Ocean View",
    image: "https://crlre.com/wp-content/uploads/Jade-House-Drone-5.jpeg",
    alt: "The Elite “Jade House” in Escaleras",
    location: "Escalares",
    title: "The Elite “Jade House” in Escaleras",
    price: "$3,100,000",
    specs: [{ label: "5", suffix: " beds" }, { label: "6.5", suffix: " baths" }, { label: "9,094 Sq.Ft. m", suffix: "" }],
    excerpt: "Perfection perched in the most desired community of Escaleras!",
    sold: false,
    featured: false,
  },
  {
    slug: "tropical-2-bedroom-villa",
    href: "https://crlre.com/properties/tropical-2-bedroom-villa/",
    tag: "Private Home",
    image: "https://crlre.com/wp-content/uploads/4-Tropical-Uvita-Villa-Costa-Rica-Luxury-Real-Estate.jpeg",
    alt: "Tropical 2 Bedroom Villa – Modern & Contemporary",
    location: "Uvita Puntarenas",
    title: "Tropical 2 Bedroom Villa – Modern & Contemporary",
    price: "$289,000",
    specs: [{ label: "2", suffix: " beds" }, { label: "1.5", suffix: " baths" }, { label: "1,290 Sq.Ft. m", suffix: "" }],
    excerpt: "This newly built TROPICAL VILLA is located just minutes from the town of Uvita and 5 minutes to Playa Hermosa beach. Being this close to...",
    sold: false,
    featured: false,
  },
  {
    slug: "tropical-lush-lot-only-mins-to-the-marina",
    href: "https://crlre.com/properties/tropical-lush-lot-only-mins-to-the-marina/",
    tag: "Lot & Land",
    image: "https://crlre.com/wp-content/uploads/7-Tropical-Residential-Lot-Quepos-CRLRE.jpg",
    alt: "Tropical Lush Lot only mins to the Marina",
    location: "Quepos Puntarenas",
    title: "Tropical Lush Lot only mins to the Marina",
    price: "$69,000",
    specs: [],
    excerpt: "This is a beautifully landscaped lot with a pedestrian & vehicle gated entrance along with a surrounding permiter wall for ultimate privacy. All the tropical...",
    sold: false,
    featured: false,
  },
  {
    slug: "new-home-outstanding-ocean-views",
    href: "https://crlre.com/properties/new-home-outstanding-ocean-views/",
    tag: "Ocean View",
    image: "https://crlre.com/wp-content/uploads/Home-25-of-83-e1639609423730.jpg",
    alt: "Tropical Uvita Villa, Mins to the Beach!",
    location: "Uvita · Puntarenas",
    title: "Tropical Uvita Villa, Mins to the Beach!",
    price: "$1,695,000",
    specs: [{ label: "6", suffix: " beds" }, { label: "6.5", suffix: " baths" }, { label: "1.73 acres m", suffix: "" }],
    excerpt: "Few properties that give people a perfect blend of luxury, beauty and convenience. However, this luxury home located in Uvita is one of such. It...",
    sold: false,
    featured: false,
  },
  {
    slug: "utopia-by-tulemar-resort",
    href: "https://crlre.com/properties/utopia-by-tulemar-resort/",
    tag: "Commercial",
    image: "https://crlre.com/wp-content/uploads/27-Utopia-Tulemar-Resort-CRLRE.jpg",
    alt: "Utopia by Tulemar Resort",
    location: "Manuel Antonio Puntarenas",
    title: "Utopia by Tulemar Resort",
    price: "$1,320,000",
    specs: [{ label: "7", suffix: " beds" }, { label: "7", suffix: " baths" }, { label: "3,507 SF m", suffix: "" }],
    excerpt: "Enjoy the newest property available in Manuel Antonio! “Utopia” – an imagined place or state of things in which everything is perfect. Utopia offers 7...",
    sold: false,
    featured: false,
  },
  {
    slug: "villa-alegria",
    href: "https://crlre.com/properties/villa-alegria/",
    tag: "Ocean View",
    image: "https://crlre.com/wp-content/uploads/VILLA-ALEGRIA-45-e1691678054163.jpg",
    alt: "VILLA ALEGRIA",
    location: "Manuel Antonio · Puntarenas",
    title: "VILLA ALEGRIA",
    price: "$1,750,000",
    specs: [{ label: "4", suffix: " beds" }, { label: "4.5", suffix: " baths" }, { label: "0.26 ACRES m", suffix: "" }],
    excerpt: "Location: Manuel Antonio, Costa Rica Welcome to Casa Alegria, an exquisite ocean view home nestled in the enchanting surroundings of Manuel Antonio. This stunning villa boasts...",
    sold: false,
    featured: false,
  },
  {
    slug: "villa-kanik-beautiful-ocean-view-luxury",
    href: "https://crlre.com/properties/villa-kanik-beautiful-ocean-view-luxury/",
    tag: "Private Home",
    image: "https://crlre.com/wp-content/uploads/Villa-Kańik-Beautiful-Ocean-view-Luxury-51-e1679086684984.jpg",
    alt: "Villa Kańik Beautiful Ocean view Luxury",
    location: "Dominical",
    title: "Villa Kańik Beautiful Ocean view Luxury",
    price: "$2,900,000",
    specs: [{ label: "5", suffix: " beds" }, { label: "4.5", suffix: " baths" }, { label: "3.34 ACRES m", suffix: "" }],
    excerpt: "Location: Escaleras, Dominical, Costa Rica Welcome to Villa Kańik – an extraordinary 5-bedroom, 4.5-bathroom luxury home located in the perfect spot just above the surf at...",
    sold: false,
    featured: false,
  },
  {
    slug: "villas-mymosa-hotel",
    href: "https://crlre.com/properties/villas-mymosa-hotel/",
    tag: "Hotels & Resorts",
    image: "https://crlre.com/wp-content/uploads/Properties/Villas-Mymosa-Hotel/villas-mymosa-hotel-costa-rica-luxury-real-estate-30.jpg",
    alt: "Villas Mymosa Hotel",
    location: "Manuel Antonio Puntarenas",
    title: "Villas Mymosa Hotel",
    price: "$1,290,000",
    specs: [{ label: "12", suffix: " beds" }, { label: "12", suffix: " baths" }, { label: "12,000 Sq.Ft m", suffix: "" }],
    excerpt: "This a modern 12 room condo hotel located in the tranquil setting of beautiful Manuel Antonio. Our spacious rooms are fully equipped to provide you...",
    sold: false,
    featured: false,
  },
  {
    slug: "white-water-view-home-in-dominical-gated-community",
    href: "https://crlre.com/properties/white-water-view-home-in-dominical-gated-community/",
    tag: "Private Home",
    image: "https://crlre.com/wp-content/uploads/White-Water-View-Home-in-Dominical-Gated-Community-21-e1675109336393.jpg",
    alt: "White Water View Home in Dominical Gated Community",
    location: "Dominical",
    title: "White Water View Home in Dominical Gated Community",
    price: "$1,350,000",
    specs: [{ label: "3", suffix: " beds" }, { label: "2.5", suffix: " baths" }, { label: "0.3 ACRES m", suffix: "" }],
    excerpt: "Location: Dominical, Costa Rica Located in a gated community, this beautiful house embraces the Costa Rica lifestyle at its finest. It’s the best location in Dominical...",
    sold: false,
    featured: false,
  },
  {
    slug: "casa-manuel-antonio-under-construction-now",
    href: "https://crlre.com/properties/casa-manuel-antonio-under-construction-now/",
    tag: "Sold",
    image: "https://crlre.com/wp-content/uploads/MA41.png",
    alt: "Casa Manuel Antonio – Scheduled for Completion September 2024!",
    location: "Manuel Antonio · Puntarenas",
    title: "Casa Manuel Antonio – Scheduled for Completion September 2024!",
    price: "$9,500,000",
    specs: [{ label: "11", suffix: " beds" }, { label: "13", suffix: " baths" }, { label: "15,000+ m", suffix: "" }],
    excerpt: "Para ver las proyecciones de alquiler – 2024/2025: Haga clic aquí ahora Bienvenido a “Casa Manuel Antonio”, ¡la nueva oportunidad de construcción de lujo que...",
    sold: true,
    featured: true,
  },
  {
    slug: "fantastic-affordable-lot-in-llanuras-del-palmar-quepos-costa-rica",
    href: "https://crlre.com/properties/fantastic-affordable-lot-in-llanuras-del-palmar-quepos-costa-rica/",
    tag: "Sold",
    image: "https://crlre.com/wp-content/uploads/SmallPicture1.jpg",
    alt: "** Fantastic AFFORDABLE Lot in Llanuras Del Palmar, Quepos, Costa Rica**",
    location: "Llanuras Del Palmar",
    title: "** Fantastic AFFORDABLE Lot in Llanuras Del Palmar, Quepos, Costa Rica**",
    price: "Contact for price",
    specs: [{ label: "253 m", suffix: "" }],
    excerpt: "Seize the opportunity to own a coveted corner lot in Llanuras Del Palmar in the heart of Quepos, Costa Rica—a gateway to realizing your vision...",
    sold: true,
    featured: false,
  },
  {
    slug: "new-dominicalito-beach-house-with-guest-villa",
    href: "https://crlre.com/properties/new-dominicalito-beach-house-with-guest-villa/",
    tag: "Sold",
    image: "https://crlre.com/wp-content/uploads/8-Las-Olas-Costa-Rica-Luxury-Real-Estate.jpg",
    alt: "NEW Dominicalito Beach House with Guest Villa",
    location: "Dominical Puntarenas",
    title: "NEW Dominicalito Beach House with Guest Villa",
    price: "$1,690,000",
    specs: [{ label: "5", suffix: " beds" }, { label: "4", suffix: " baths" }, { label: "5,000 Sq.Ft. m", suffix: "" }],
    excerpt: "Walk to beach, modern & contemporary, equipped with solar panels",
    sold: true,
    featured: false,
  },
  {
    slug: "titi-condo-7-poolside-unit",
    href: "https://crlre.com/properties/titi-condo-7-poolside-unit/",
    tag: "Sold",
    image: "https://crlre.com/wp-content/uploads/Unit-7-Titi-Condo-Manuel-Antonio-19.jpeg",
    alt: "Titi Condo #7 – Poolside Unit",
    location: "Manuel Antonio Puntarenas",
    title: "Titi Condo #7 – Poolside Unit",
    price: "$145,000",
    specs: [{ label: "2", suffix: " beds" }, { label: "1", suffix: " baths" }, { label: "544 sq.ft. m", suffix: "" }],
    excerpt: "This is the best value property in Manuel Antonio and located off the main drive which means you are just mins away to everything i.e....",
    sold: true,
    featured: false,
  },
] satisfies readonly Listing[];
